// Legacy static Colors export — kept for backward compatibility.
// Screens/components should use useTheme() from ThemeContext for dynamic theming.
export const Colors = {
  primary: '#E8636E',
  primaryLight: '#FFF0F1',
  primaryDark: '#D14D58',
  accent: '#2EC4B6',
  accentLight: '#E0F7F5',
  background: '#FAFAF8',
  surface: '#FFFFFF',
  surfaceAlt: '#F5F5F3',
  textPrimary: '#2D2D3F',
  textSecondary: '#6B7280',
  textDisabled: '#9CA3AF',
  textOnPrimary: '#FFFFFF',
  error: '#EF4444',
  warning: '#F59E0B',
  success: '#10B981',
  muscleActive: '#E8636E',
  muscleSecondary: '#2EC4B6',
  muscleInactive: '#F0F0ED',
  border: '#F0F0ED',
  borderFocus: '#E8636E',
  glow: 'rgba(232,99,110,0.3)',
} as const;
